language: python
python:
  - "3.6"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python setup.py install"
  - "pip install coverage"
# command to run tests
script:  bash -xe test.sh
